---
name: Vulnerability Scan

on:
  schedule:
    - cron: "30 2 * * *"
  workflow_dispatch:

jobs:
  repository:
    name: Get Repository Apps
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.repository.outputs.items }}
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Get Apps
        uses: ./.github/actions/app-inventory
        id: repository

  grype:
    name: Download Grype
    runs-on: ubuntu-latest
    steps:
      - name: Install Grype
        uses: anchore/scan-action/download-grype@62b74fb7bb810d2c45b1865f47a77655621862a5 # v7.2.3
        id: grype

      - name: Update Database
        run: ${{ steps.grype.outputs.cmd }} db update

      - name: Create Cache Key
        id: cache
        run: echo "key=$(date -u +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Cache Database
        uses: actions/cache/save@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
        with:
          key: grype-db-${{ steps.cache.outputs.key }}
          path: ~/.cache/grype/db

  vulnerability-scan:
    needs: ["repository", "grype"]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        apps: ${{ fromJSON(needs.repository.outputs.apps) }}
      max-parallel: 4
      fail-fast: false
    permissions:
      security-events: write
    steps:
      - name: Setup Vars
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        id: vars
        with:
          script: |
            core.setOutput('repository-owner', '${{ github.repository_owner }}'.toLowerCase());

      - name: Retreive Cache Key
        id: cache
        run: echo "key=$(date -u +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Restore Database
        uses: actions/cache/restore@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
        with:
          key: grype-db-${{ steps.cache.outputs.key }}
          path: ~/.cache/grype/db

      - name: Scan
        uses: anchore/scan-action@62b74fb7bb810d2c45b1865f47a77655621862a5 # v7.2.3
        id: scan
        with:
          fail-build: false
          image: ghcr.io/${{ steps.vars.outputs.repository-owner }}/${{ matrix.apps.name }}:rolling

      - name: Upload Report
        uses: github/codeql-action/upload-sarif@1b549b9259bda1cb5ddde3b41741a82a2d15a841 # v3.28.13
        with:
          category: ${{ matrix.apps.name }}
          sarif_file: ${{ steps.scan.outputs.sarif }}
